export let homeMain = {
    "innerHTML": "<div class='Home'><div class='header'><img src='./r2.png' /><img id='img2' src='./lk.png' /><div/><div class='Sdays'><ul class='trteb'><li><h3>Special Days<h3/></li><li><img  src='./145.jpg'/><p>World Environment Day 22/04</p></li><li><img  src='./day2.webp'/><p>Earth Day 05/06</p></li><li><img  src='./day1.jpg'/><p>Arbor Day 29/04</p></li></div></div><div class='container'><div class='pI'><div class='para'><p>This Website Collects For You Activities You Can Join And Brands You Love Who Supports Recycling ,You Can Start Recycle & Take Part of It Hoping you'll enjoy❣</p></div></div></div><div class='buttom'><ul class='homeUls'><li><h3>Recycling Brands:</h3></li><li><img  src='./hm.jpg'/></li><li><img  src='./sfr.jpg'/></li><li><img  src='./adidas.jpg'/></li><li><img  src='./miEden.jpg'/></li><li><img  src='./Shufersal.jpg'/></li><li><img  src='./nespresso.png'/></li><li><img  src='./mac.png'/></li><a href='./brands'><li class='href'><img  src='./fm.png'/></li></a></ul></div><div/>"

}


//   <div class='Main'><div class='boardNote'><p>Top Activities -> cleaning Event-19/4<button>1500 Join</button></p></div><div class='champs'><h4>Recycling Challenge Champs🏆</h4><div class='winnErs'><div class='firstP'><h5>Yara</h5><h6>Recycling Amount:150</h6></div><div class='firstP' ><h5>Yoni</h5><h6>Recycling Amount:100</h6></div><div class='firstP'><h5>Mor</h5><h6>Recycling Amount:70</h6></div></div></div></div><div class='buttom'><ul class='homeUls'><li><img  src='./adidas.jpg'/></li><li><img  src='./miEden.jpg'/></li><li><img  src='./Shufersal.jpg'/></li><li><img  src='./nespresso.png'/></li><li><img  src='./mac.png'/></li></ul></div></div>"
//  <li><a href='./brands'>For More ..</a></li>
///<div class='buttom'><ul class='homeUls'><li><img  src='./hm.jpg'/></li><li><img  src='./sfr.jpg'/></li><li><img  src='./Shufersal.jpg'/></li><li><img  src='./nespresso.png'/></li><li><img  src='./mac.png'/></li></ul></div>

//<div class='buttom'><ul class='homeUls'><li><img  src='./day2.jpg'/><p>22/04/22</p></li><li><img  src='./day3.webp'/><p>05/06/22</p></li><li><img  src='./day1.jpg'/><p>29/04/22</p></li></div></div>